### ISSUE TITLE
Host your website live on GitHub Pages.

### ISSUE THREAD

**Issue by numanzamandipuu** [vedant-z/Score-Keeper#1]
### Greetings.
I found out about your project from [IdeaHub](https://ideashub.netlify.app/projects). it would be great if you make your project online using GitHub pages because sometimes it is annoying to download the entire project and use that on a local machine.
Consider renaming the `Score.html` file to `index.html`, then go to [Pages](https://github.com/vedant-z/Score-Keeper/settings/pages) and deploy your website online.
You can get documentation about GitHub Pages on [here](https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-github-pages-site). <br>
Good Day!

**Comment by vedant-z** [comment]
Hey @numanzamandipuu 

I got your point but currently I have deployed my another project on GitHub pages and as you might be knowing you can deploy only one project from an account.....

So, I will think of deploying it another day.

**Comment by numanzamandipuu** [comment]
You can obviously deploy multiple projects to GitHub pages from one account. GitHub Pages doesn't have any restriction regarding that.
**IF YOU WANT** then kindly rename your  `Score.html` file to `index.html` and go to [this link](https://github.com/vedant-z/Score-Keeper/settings/pages), you'll see something like this. <br>
![image](https://user-images.githubusercontent.com/72611571/191456779-5bbb6843-35c7-40ab-be49-d250998c1f64.png)
<br>
### then from Branch, click main, 
Note: You won't see D10, that is my branch :pensive:
<br>
![image](https://user-images.githubusercontent.com/72611571/191457559-bedcd996-87be-4b57-9306-bac02de410ee.png)
<br> 
### after that, hit save and you are good to go!
![image](https://user-images.githubusercontent.com/72611571/191457927-50814215-06ce-4f8e-a5a1-df98c0bd5516.png)
<br>
After 2-3 minutes, your site will be live on this link - https://vedant-z.github.io/Score-Keeper/
Note: You must rename your main file to `index.html`
My point is not to force you to do anything like this, I just want to say that you can host as many project you want to GitHub pages. Just remember to keep your main file as `index.html`

**Comment by vedant-z** [comment]
@numanzamandipuu Thanks a lot 

See I have deployed it. I hope you like it.

**Comment by numanzamandipuu** [comment]
You got a cool UI :sparkles:
Please consider closing this issue as completed.
